#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     spin,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    gripL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    gripR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"     // Tells ROBOTC to include the driver file for the joystick.

void Arcade(int x, int y) // make joystick arcade style controller
{
	int powY;
	int powX;
	int powRightMotor;
	int powLeftMotor;

	// convert joystick -128 to 127 range to -100 to 100 for powering motors
	powY = (y * 100) / 127;         // joystick y axis gives maximum power level
	powX = (x * 100) / 127;         // x axis determines which motor is reduced or
	// reversed for a turn

	if (powX < 0) //  if x negative, turning left; otherwise, turning right
	{
		powLeftMotor = (powY * (100 + (2 * powX))/100); // left motor reduced for right turn
		powRightMotor = powY;                           // right motor not changed
	}
	else
	{
		powRightMotor = (powY * (100 - (2 * powX))/100); // right motor reduced for left turn
		powLeftMotor = powY;                            // left motor not changed
	}

	motor[right] = powRightMotor;
	motor[left]  = powLeftMotor;

	//if (powY < 10){
	//	motor[right] = 0;
	//		motor[left] = 0;
	// 	}

	//    if (powY < -10){
	//    		motor[right] = 0;
	//    		motor[left] = 0;
	//    	}

}

//Buttons

void Buttons()
{

	//spinner settings

	if (joy2Btn (6) == 1)
	{
		motor[spin] = -10;
		//joy1Btn (5) = 0;
	}
	else
	{
		//motor[spin] = 0;

		if (joy2Btn (5) == 1)
		{
			motor[spin] = 100;
		}
		else
		{
			motor[spin] = 0;
		}
	}

		//Gripping servos grab

		if (joy2Btn (7) == 1)
		{
			servo[gripR] = 190;
			servo[gripL] = -10;
		}
		else
		{
			servo[gripR] = 80;
			servo[gripL] = 190;
		}

		//Arm
		if (joy2Btn (1) == 1)
	{
		motor[arm] = -100;

	}
	else
	{
		//motor[spin] = 0;

		if (joy2Btn (3) == 1)
		{
			motor[arm] = 100;
		}
		else
		{
			motor[arm] = 0;
		}

	}

}

void Lift(int x, int y) // controller 2 will raise and lower our arm
{
	int powY;
	int powX;
	//int powRightMotor;
	int powliftMotor;

	// convert joystick -128 to 127 range to -100 to 100 for powering motors
	powY = (y * 100) / 127;         // joystick y axis gives maximum power level
	powX = (x * 100) / 127;         // x axis determines which motor is reduced or
	// reversed for a turn

	if (powY < 0) //  if y negative
	{
		powliftMotor = (powY * (100 + (2 * powX))/100); // left motor reduced for right turn
		//powArmMotor = powY;                           // right motor not changed
	}
	else
	{
		powliftMotor = (powY * (100 - (2 * powX))/100); // right motor reduced for left turn
		//powArmMotor = powY;                            // left motor not changed
	}

	if (powY < 10){
		motor[lift] = 0;
	}

	if (powY < -10){
		motor[lift] = 0;
	}

	motor[lift] = powliftMotor;
}



task main()
{

	while (true)
	{

		Lift(1, joystick.joy2_y1);

		Buttons();

		getJoystickSettings(joystick);

		Arcade(joystick.joy1_x2, joystick.joy1_y1);

	}

}
